### ISSUE TITLE
Missed replacement field for string?

### ISSUE THREAD

**Issue by brushtab** [lkhq/laniakea-spark#1]
Hello.

You probably missed "{}" in string:

https://github.com/lkorigin/laniakea-spark/blob/aa987b8fe1aa1eba1de9f0cc470deb3b93304244/spark/runners/image_build.py#L68

Maybe it should be something like this:

` results_dir = '/srv/artifacts/{}'.format(job_id) `

**Comment by ximion** [comment]
Drats, really ugly!
The result was correct though, there should have been no substitution happening at all.
I resolved this, and also removed an additional copy operation (that was probably done in a time where runners didn't produce a list of files to upload yet - we shouldn't need to copy possibly gigabyte-sized files around for no reason anymore)
